name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Kết nối ssh linux -> và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /var/www/server/MyxNovel_server
          git pull
          git status
          . $HOME/.nvm/nvm.sh
          nvm use
          npm ci
          echo "Khởi tạo prisma Client cho node module"
          npx prisma generate
          npm run build
          sudo swapoff -a; sudo swapon -a
          pm2 delete all
          pm2 start dist/main.js
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.DC_KEY }}" -d '{"content":"Dự án node js đã deploy thành công link: ${{ secrets.SV_HOST }} "}' ${{ secrets.DC_URL }} 
